"""Add source_type to camera table

Revision ID: d85313399ea6
Revises: 4a121db80d3b
Create Date: 2025-10-22 20:55:42.701237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85313399ea6'
down_revision: Union[str, None] = '4a121db80d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('source_type', sa.Enum('WEBCAM', 'RTSP', 'FILE', 'HTTP', name='sourcetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'source_type')
    # ### end Alembic commands ###
